%% TEST TRANSITION MATRIX =================================================
%
%   Test the extent to which the transition matrix recapitulates
%   Fokker-Plank dynamics for a known potential
%
%   by Dillon Cislo 2024/04/24
%==========================================================================

%% Generate Analytic Results for Specified Potential ======================
clear; close all; clc;

%--------------------------------------------------------------------------
% Generate Analytic Results For Base Potential
%--------------------------------------------------------------------------
fprintf('Performing symbolic analysis of base potential... ');

syms x y
assume(x, 'real');
assume(y, 'real');

% Generate 2D potential ---------------------------------------------------

% p3 = -0.75; p4 = 0.4; % Deep wells 
p3 = -0.5; p4 = 0.1; % Shallow wells

% 3-well heteroclinic flip potential
U = x.^4 + y.^4 + x.^3 - 2.*x.*y.^2 - x.^2 + p3*x + p4*y;

% Perform symbolic analysis -----------------------------------------------
gradU = simplify(gradient(U, [x y]));
delU = simplify(laplacian(U, [x,y]));

% Generate anonymous functions from analytic statements
symU = U;
UFunc = matlabFunction(U, 'Vars', {x, y});
gradUFunc = matlabFunction(gradU.', 'Vars', {x, y});
delUFunc = matlabFunction(delU, 'Vars', {x, y});

% Find fixed points of the deterministic gradient flow numerically
fixedPts = vpasolve([gradU(1) == 0; gradU(2) == 0], [x y]);
fixedPts = double([fixedPts.x(:), fixedPts(:).y]);

% Assess stability of fixed points
J = simplify([gradient(-gradU(1), [x, y]), gradient(-gradU(2), [x y])].');
% fpEigV = zeros(size(fixedPts1,1), 
fpLambda = zeros(size(fixedPts,1), 1);
for i = 1:numel(fpLambda)
    numJ = double(vpa(subs(J, {x, y}, {fixedPts(i,1), fixedPts(i,2)})));
    fpLambda(i) = max(real(eig(numJ)));
end

% Re-order fixed points by largest (real) eigenvalue
[fpLambda, sortOrder] = sort(fpLambda, 'ascend');
fixedPts = fixedPts(sortOrder, :);

fprintf('Done\n');

%--------------------------------------------------------------------------
% Convert to Numerical Results
%--------------------------------------------------------------------------
fprintf('Converting to numerical results... ');

xLim = [-2 2];
yLim = [-2 2];
numPoints = 100;
[X, Y] = meshgrid(linspace(xLim(1), xLim(2), numPoints), ...
    linspace(yLim(1), yLim(2), numPoints));

% A set of node IDs for each grid point
gridIDx = reshape((1:numel(X)).', size(X));

% A list of boundary node IDs
bdyIDx = false(size(X));
bdyIDx(1,:) = true; bdyIDx(end,:) = true;
bdyIDx(:,1) = true; bdyIDx(:,end) = true;
bdyIDx = find(bdyIDx(:));

gridU = UFunc(X(:), Y(:));

fprintf('Done\n');

%--------------------------------------------------------------------------
% View Results
%--------------------------------------------------------------------------

crange = [min(min(gridU(:)), min(gridU(:))), 2];

UColors = vals2colormap(gridU(:), 'parula', crange); 
UColors = cat( 3, reshape(UColors(:,1), size(X)), ...
    reshape(UColors(:,2), size(X)), reshape(UColors(:,3), size(X)) );

sinkIDx = fpLambda < 0;
saddleIDx = fpLambda >= 0;

numContours = linspace(min(gridU(:)), 2, 15);

fig = figure;
clear axArray

axArray(1) = subplot(1,2,1);
surf(X, Y, reshape(gridU, size(X)), UColors);
hold on
scatter3(fixedPts(sinkIDx, 1), fixedPts(sinkIDx, 2), ...
    UFunc(fixedPts(sinkIDx, 1), fixedPts(sinkIDx, 2)), ...
    'filled', 'r');
scatter3(fixedPts(saddleIDx, 1), fixedPts(saddleIDx, 2), ...
    UFunc(fixedPts(saddleIDx, 1), fixedPts(saddleIDx, 2)), ...
    'filled', 'g');
hold off

xlabel('x'); ylabel('y');
axis equal
zlim([1.05 * min(gridU(:)), 2]);
% colorbar
set(gca, 'Clim', crange);
title('Initial Potential U_1');

subplot(1,2,2)
contourf(X, Y, reshape(gridU, size(X)), numContours);
hold on
scatter(fixedPts(sinkIDx, 1), fixedPts(sinkIDx, 2), 'filled', 'r');
scatter(fixedPts(saddleIDx, 1), fixedPts(saddleIDx, 2), 'filled', 'g');
hold off
colorbar
% set(gca, 'Clim', [min(min(gridU1(:)), min(gridU2(:))), max(gridU1)]);
set(gca, 'Clim', crange);
set(gca, 'YDir', 'normal');
axis equal tight
title('Initial Potential U_1');

clear i J numJ numPoints saddleIDx sinkIDx sortOrder x y fpU
clear D p3 p4 crange gridU gridGradU gridDelU
clear U1 UColors axArray Link fig numContours

%% Generate Points by Simulating Stochastic ODE ===========================
% Points are generated by simulating drift-diffusion dynamics using the
% BASE potential
% close all; clc;

rng(88, 'twister');
% rng(25, 'twister'); % For reproducible random numbers

D0 = 0.2; % 1; % Diffusion coefficient
numPoints = 1e4; % 5000; % Total number of points
numTimePts = 50000; % Number of time steps for each simulation
dtSODE = 0.01; % Simulation time step

% Initialize simulation points
simX = repmat(fixedPts(2,:), numPoints, 1) + (0.3 * rand(numPoints,2)-0.15);

% The time at which each simulation will be terminated
stopTimes = randsample(numTimePts, numPoints, true);

% List of simulations that are still active
activeIDx = stopTimes > 1;
stopTimes(~activeIDx) = [];
activeIDx = find(activeIDx);

t = 2;

fprintf('Generating points via stochastic simulation:\n');
% profile on
while (~isempty(activeIDx) && (t <= numTimePts))
    
    numActive = numel(activeIDx);
    progressbar(numPoints-numActive, numPoints)
    
    % Update active points
    gradUXY = gradUFunc(simX(activeIDx, 1), simX(activeIDx, 2));
    simX(activeIDx, :) = simX(activeIDx, :) - dtSODE * gradUXY + ...
        sqrt(2 * dtSODE * D0) * normrnd(0, 1, [numActive 2]);
    
    % Determine which points are still active
    curStop = stopTimes == t;
    activeIDx(curStop) = [];
    stopTimes(curStop) = [];
    t = t+1;
    
end
% profile viewer

clear activeIDx stopTimes numActive t gradUXY curStop

%--------------------------------------------------------------------------
% View Results
%--------------------------------------------------------------------------

simColors = UFunc(simX(:,1), simX(:,2));
crange = [min(simColors), 2];

sinkIDx = fpLambda < 0;
saddleIDx = fpLambda >= 0;

subplot(1,3,1)
scatter(simX(:,1), simX(:,2), [], simColors, 'x');
hold on
scatter(fixedPts(sinkIDx, 1), fixedPts(sinkIDx, 2), ...
    'filled', 'r');
scatter(fixedPts(saddleIDx, 1), fixedPts(saddleIDx, 2), ...
    'filled', 'g');
hold off
axis equal tight
xlim([-2 2]);
ylim([-2 2]);
xlabel('x', 'Color', 'w'); ylabel('y', 'Color', 'w')
set(gca, 'Color', 'k');
set(gca, 'XColor', 'w');
set(gca, 'YColor', 'w');
set(gca, 'Clim', crange);
title('2D Simulated Point Locations', 'Color', 'w');

subplot(1,3,2)
pcshow([simX(:,1), simX(:,2), UFunc(simX(:,1), simX(:,2))], simColors);
hold on
scatter3(fixedPts(sinkIDx, 1), fixedPts(sinkIDx, 2), ...
    UFunc(fixedPts(sinkIDx, 1), fixedPts(sinkIDx, 2)), ...
    'filled', 'r');
scatter3(fixedPts(saddleIDx, 1), fixedPts(saddleIDx, 2), ...
    UFunc(fixedPts(saddleIDx, 1), fixedPts(saddleIDx, 2)), ...
    'filled', 'g');
hold off
xlim(xLim);
ylim(yLim);
xlabel('x'); ylabel('y'), zlabel('U(x,y)');
set(gca, 'Color', 'k');
set(gca, 'Clim', crange);
title('3D Simulated Point Locations');
axis equal tight
camproj('orthographic');

subplot(1,3,3)
nBins = 20;
hist3([simX(:,1), simX(:,2)], 'Edges', {linspace(xLim(1), xLim(2), nBins), ...
    linspace(yLim(1), yLim(2), nBins)});
title('Simulated Point Density Distribution', 'Color', 'w');
set(gca, 'XColor', 'w');
set(gca, 'YColor', 'w');
set(gca, 'ZColor', 'w');
set(gca, 'Color', 'k');
set(gca, 'GridColor', 'w');
grid on

clear timeColors nBins sinkIDx saddleIDx
clear numInitPts numTimePts simColors t crange
clear dtSODE

%% ************************************************************************
% *************************************************************************
%           ASSESS QUALITY OF INFERRED UNSTABLE MANIFOLDS
% *************************************************************************
% *************************************************************************

%% Build Transition Matrix and Compute Most Probable Paths ================
close all; clc;

D = 0.025;
dt = 1e-2; % <---- THE DYNAMICAL TIME STEP
scalarMetric = 1;
simU = UFunc(simX(:,1), simX(:,2));

volumeType = 'GraphLaplacian';
if strcmpi(volumeType, 'LaplaceBeltrami')
    simU0 = simU;
elseif strcmpi(volumeType, 'GraphLaplacian')
    simU0 = -log(gaussianKDE(simX, simX, [], sqrt(2 * dt), false, ...
        [], [], true));
else
    error('Invalid volume element type');
end

T = computeTransitionMatrix(simX, simU, dt, ...
    'PointDiffusionCoefficient', D, 'DiffusionCoefficient', D, ...
    'ClipThreshold', 1e-12, 'StrictNormalization', true, 'useGPU', true, ...
    'PointPotential', simU0, 'VolumeElementType', volumeType, ...
    'ScalarMetric', scalarMetric);

% For deep wells
% pathPairIDx = [knnsearch(simX, fixedPts([2, 1], :)), ...
%     knnsearch(simX, fixedPts([1, 3], :))];

% For shallow wells
pathPairIDx = [knnsearch(simX, fixedPts([1, 2], :)), ...
    knnsearch(simX, fixedPts([2, 3], :))];

[allPaths, allPathLengths, allPathWeights] = computeMostProbablePaths( ...
    simX, T, pathPairIDx, []);

basinLocIDx = knnsearch(simX, fixedPts(fpLambda < 0, :));
[basinProb, basinCounts, basinIDx] = computeBasins(simX, T, ...
    ones(numPoints, 1) ./ numPoints, basinLocIDx, ...
    'DistanceMethod', 'Probability');

for i = 1:numel(basinLocIDx)
    fprintf('Total Probability for (%0.2f, %0.2f) = %0.4f\n', ...
        simX(basinLocIDx(i), 1), simX(basinLocIDx(i), 2), basinProb(i));
end

%--------------------------------------------------------------------------
% View Results
%--------------------------------------------------------------------------

sinkIDx = fpLambda < 0;
saddleIDx = fpLambda >= 0;

% View Potential and Unstable Manifolds -----------------------------------

crange = [min(simU), 0.2];
pointColors = vals2colormap(simU, 'parula', crange);

figure('Color', 'k');

subplot(1,2,1)
scatter(simX(:,1), simX(:,2), [], pointColors, 'x');

hold on

for i = 1:numel(allPaths)
    line(simX(allPaths{i}, 1), simX(allPaths{i}, 2), ...
        'Color', 'm', 'LineWidth', 2, 'Marker', 'o', ...
        'MarkerFaceColor', 'c', 'MarkerEdgeColor', 'm');
end

scatter(fixedPts(sinkIDx, 1), fixedPts(sinkIDx, 2), ...
    'filled', 'r', 'MarkerEdgeColor', 'k', 'LineWidth', 2);
scatter(fixedPts(saddleIDx, 1), fixedPts(saddleIDx, 2), ...
    'filled', 'g', 'MarkerEdgeColor', 'k', 'LineWidth', 2);

hold off

axis equal
xlim([-2 2]);
ylim([-2 2]);
set(gca, 'XColor', 'w');
set(gca, 'YColor', 'w');
set(gca, 'ZColor', 'w');
set(gca, 'Color', 'k');
set(gca, 'GridColor', 'w');
grid on
box on
cb = colorbar('Color', 'w');
cb.Label.String = ('U');
set(gca, 'Clim', crange)
title(sprintf(['Volume Element: ' volumeType '\n' ...
    'D_0 = %0.2f, D = %0.2f, dt = %0.4f, g = %0.4f'], ...
    D0, D, dt, scalarMetric), 'Color', 'w')

% View Basins of Attraction -----------------------------------------------

basinColors = distinguishable_colors(numel(basinLocIDx), ...
    [0 0 0; 1 1 1; 0 1 0; 1 0 1; 0 1 1]);

allBasinColors = basinColors(basinIDx, :);

subplot(1,2,2);
scatter(simX(:,1), simX(:,2), [], allBasinColors, 'x');

hold on

for i = 1:numel(allPaths)
    line(simX(allPaths{i}, 1), simX(allPaths{i}, 2), ...
        'Color', 'm', 'LineWidth', 2, 'Marker', 'o', ...
        'MarkerFaceColor', 'c', 'MarkerEdgeColor', 'm');
end

scatter(fixedPts(sinkIDx, 1), fixedPts(sinkIDx, 2), ...
    [], basinColors, 'filled', 'MarkerEdgeColor', 'k', ...
    'LineWidth', 2);
scatter(fixedPts(saddleIDx, 1), fixedPts(saddleIDx, 2), ...
    'filled', 'g', 'MarkerEdgeColor', 'k', 'LineWidth', 2);

hold off

axis equal
xlim([-2 2]);
ylim([-2 2]);
set(gca, 'XColor', 'w');
set(gca, 'YColor', 'w');
set(gca, 'ZColor', 'w');
set(gca, 'Color', 'k');
set(gca, 'GridColor', 'w');
grid on
box on
set(gca, 'Clim', [1 numel(basinLocIDx)]);
set(gca, 'Colormap', basinColors);
cb2 = colorbar('Ticks', 1:numel(basinLocIDx), 'Color', 'w');
cb2.Label.String = 'Basin #';
title('Basins of Attraction', 'Color', 'w');


clear crange pointColors sinkIDx saddleIDx cb
clear basinColors allBasinColors cb2



%% ************************************************************************
% *************************************************************************
%                       ASSESS QUALITY OF DYNAMICS
% *************************************************************************
% *************************************************************************

%% Solve the Fokker-Planck Equation Using Finite Differences ============
close all; clc;

D = 1;
dt = 5e-3; % <---- THE DYNAMICAL TIME STEP
scalarMetric = 1; % 0.0125;
simU = UFunc(simX(:,1), simX(:,2));

% xLim = [-2 2];
% yLim = [-2 2];
numGridPts = 100;
[X, Y] = meshgrid(linspace(xLim(1), xLim(2), numGridPts), ...
    linspace(yLim(1), yLim(2), numGridPts));

% Initial density
sigma = 0.1;
initDensity = (X-fixedPts(1,1)).^2 + (Y-fixedPts(1,2)).^2;
initDensity = exp(-initDensity / (2 * sigma.^2));
initDensity = initDensity ./ (2*pi*(sigma^2))^(1/2);

FPU = reshape(UFunc(X(:), Y(:)), size(X)) ./ scalarMetric; 
timeSpan = [0 5]; % Time span for integration

FPSol = solveFokkerPlanck2DFD(X, Y, initDensity, ...
    'U', reshape(FPU, size(X)), ...
    'DirichletBoundaryConditions', [], 'TimeSpan', timeSpan, ...
    'FokkerPlanckType', 'Forward', 'IntegratorType', 'non-stiff', ...
    'D', D, 'Display', 'iter');

clear numGridPts % sigma

%% View Results ===========================================================
close all; clc;

numTimePoints = 50;
timePoints = linspace(timeSpan(1), timeSpan(2), numTimePoints);
% timePoints = linspace(timeSpan(1), 2, numTimePoints);

imref = imref2d(size(X), [min(X(:)), max(X(:))], [min(Y(:)), max(Y(:))]);

totalDensity = zeros(numTimePoints, 1);
fig = figure('Color', 'k', 'units', 'normalized', 'outerposition', [0 0 1 1]);

equiDensity = reshape(exp(-FPU./D), size(X));
equiDensity = equiDensity ./ sum(equiDensity(:)) .* sum(initDensity(:));

sinkIDx = fpLambda < 0;
saddleIDx = fpLambda >= 0;

for tidx = 1:numTimePoints
    
    t = timePoints(tidx);
    curDensity = reshape(deval(FPSol, t), size(X));
    
    totalDensity(tidx) = sum(curDensity(:));
    
    densityRange = [min(curDensity(:)), max(curDensity(:))];
    densityIm = vals2colormap(curDensity(:), 'parula', densityRange);
    densityIm = cat(3, reshape(densityIm(:,1), size(X)), ...
        reshape(densityIm(:,2), size(X)), reshape(densityIm(:,3), size(X)));

    densityErr = abs(curDensity-equiDensity);
    errorRange = [0, max(densityErr(:))];
    errorIm = vals2colormap(densityErr(:), 'parula', errorRange);
    errorIm = cat(3, reshape(errorIm(:,1), size(X)), ...
        reshape(errorIm(:,2), size(X)), reshape(errorIm(:,3), size(X)));

    subplot(1,2,1)
    imshow(densityIm, imref);
    hold on
    scatter(fixedPts(sinkIDx, 1), fixedPts(sinkIDx, 2), ...
        'filled', 'r');
    scatter(fixedPts(saddleIDx, 1), fixedPts(saddleIDx, 2), ...
        'filled', 'g');
    hold off
    
    if (tidx == 1), set(fig, 'outerposition', [0 0 1 1]); end
    
    titleString = sprintf('T = %0.3f, Total Density = %0.3f\n', ...
        t, totalDensity(tidx));
    title(titleString, 'Color', 'w');
    xlabel('x'); ylabel('y');
    
    set(gca, 'YDir', 'normal');
    set(gca, 'XColor', 'w');
    set(gca, 'YColor', 'w');
    set(gca, 'Clim', densityRange);
    axis equal tight
    
    colorbar('Color', 'w')
    
    subplot(1,2,2)
    imshow(errorIm, imref);
    hold on
    scatter(fixedPts(sinkIDx, 1), fixedPts(sinkIDx, 2), ...
        'filled', 'r');
    scatter(fixedPts(saddleIDx, 1), fixedPts(saddleIDx, 2), ...
        'filled', 'g');
    hold off
    
    if (tidx == 1), set(fig, 'outerposition', [0 0 1 1]); end
    
    titleString = sprintf(['Approach to Equilibrium\n' ...
        'T = %0.3f, Max Error = %0.3e\n'], t, max(densityErr(:)));
    title(titleString, 'Color', 'w');
    xlabel('x'); ylabel('y');
    
    set(gca, 'YDir', 'normal');
    set(gca, 'XColor', 'w');
    set(gca, 'YColor', 'w');
    set(gca, 'Clim', errorRange);
    axis equal tight
    
    colorbar('Color', 'w')
    
    drawnow
    
end

clear numTimePoints timePoints imref totalDensity
clear equiDensity sinkIDx saddleIDx
clear curDensity densityRange densityIm densityErr
clear errorRange errorIm titleString

%% Solve the Fokker-Planck Equation Using Path Integral Methods =============
close all; clc;

numViewTimes = 100;
numTimeSteps = 5e3;

fprintf('Estimating base potential... ');
simU = UFunc(simX(:,1), simX(:,2));
simU0 = -log(gaussianKDE(simX, simX, [], sqrt(2 * dt), false, ...
        [], [], true));
fprintf('Done\n');

fprintf('Constructing volume element... ');
volumeType = 'LaplaceBeltrami';
if strcmpi(volumeType, 'LaplaceBeltrami')

    affinityOptions = struct();
    affinityOptions.Sigma = dt;
    affinityOptions.NumNeighbors = numPoints;
    affinityOptions.Verbose = false;
    K = affinityMatrix(simX, affinityOptions);

    mapOptions = struct();
    mapOptions.Normalization = 'LaplaceBeltrami';
    mapOptions.NumVectors = 0;
    mapOptions.Verbose = false;
    [~, ~, ~, ~, DAlpha] = diffusionMap(K, mapOptions);
    volumeElement = full(DAlpha);

    clear affinityOptions K mapOptions DAlpha

elseif strcmpi(volumeType, 'GraphLaplacian')

    volumeElement = exp(simU0 / D0);

else

    error('Invalid volume element type');

end
fprintf('Done\n');

fprintf('Computing transition matrix... ');
T = computeTransitionMatrix(simX, simU, dt, ...
    'PointDiffusionCoefficient', D0, 'DiffusionCoefficient', D, ...
    'ClipThreshold', 1e-12, 'StrictNormalization', true, 'useGPU', true, ...
    'PointPotential', simU0, 'VolumeElementType', volumeType, ...
    'ScalarMetric', scalarMetric, 'VolumeElement', volumeElement);
fprintf('Done\n');

fprintf('Computing initial probability... ');
initProb = (simX(:,1)-fixedPts(1,1)).^2 + (simX(:,2)-fixedPts(1,2)).^2;
initProb = volumeElement .* exp(-initProb / (2 * sigma.^2));
initProb = initProb ./ sum(initProb);
fprintf('Done\n');

fprintf('Time evolving probabilities... ');
[allProbabilities, viewTimes] = evolveProbabilities(initProb, T, ...
    numTimeSteps, 'NumViewTimes', numViewTimes, 'TimeStep', dt);
fprintf('Done\n');

%% View Results ===========================================================
close all; clc;

sinkIDx = fpLambda < 0;
saddleIDx = fpLambda >= 0;

fig = figure('Color', 'k', 'units', 'normalized', ...
    'outerposition', [0 0 1 1]);

dx = X(1,2)-X(1,1);
dy = Y(2,1)-Y(1,1);
dA = dx*dy;

nnIDx = knnsearch(simX, [X(:), Y(:)]);

viewType = 'Probability Density';
assert(ismember(viewType, {'Probability', 'Probability Density'}), ...
    'Invalid plot type');
for tidx = 1:numel(viewTimes)

    t = viewTimes(tidx);

    curProb = allProbabilities(:, tidx);
    % curProbFD = reshape(deval(FPSol, t), size(X));
    
    if strcmp(viewType, 'Probability')
        % % curProbFD = curProbFD * dA;
        % curProbFD = curProbFD ./ sum(curProbFD);
    elseif strcmpi(viewType, 'Probability Density')
        curProb = numPoints * allProbabilities(:, tidx) ./ volumeElement;
    else
        error('Invalid plot type');
    end

    % curProbFD = accumarray(nnIDx, curProbFD(:), size(curProb));
    % % probInterp = griddedInterpolant(X.', Y.', curProbFD.');
    % % curProbFD = probInterp(simX(:,1), simX(:,2));

    % Plot Path Integral Results ------------------------------------------

    crange = prctile(curProb, [0 99]);
    probColors = vals2colormap(curProb, 'parula', crange);

    subplot(1,2,1);
    scatter(simX(:,1), simX(:,2), [], probColors, 'filled');

    hold on

    scatter(fixedPts(sinkIDx, 1), fixedPts(sinkIDx, 2), 'filled', 'r');
    scatter(fixedPts(saddleIDx, 1), fixedPts(saddleIDx, 2), 'filled', 'g');

    hold off

    axis equal square
    xlim(xLim);
    ylim(yLim);
    set(gca, 'XColor', 'w');
    set(gca, 'YColor', 'w');
    set(gca, 'ZColor', 'w');
    set(gca, 'Color', 'k');
    set(gca, 'GridColor', 'w');
    grid on
    box on
    cb = colorbar('Color', 'w');
    cb.Label.String = viewType;
    set(gca, 'Clim', crange)
    title(sprintf(['Path Integral, t = %0.3f\n' ...
        'Volume Element: ' volumeType '\n'...
        'D_0 = %0.2f, D = %0.2f, dt = %0.4f, g = %0.4f'], ...
        t, D0, D, dt, scalarMetric), 'Color', 'w')

    % Plot Finite Difference Results --------------------------------------

    % crange = prctile(curProbFD, [0 98]);
    % probColors = vals2colormap(curProbFD, 'parula', crange);
    % 
    % subplot(1,2,2);
    % scatter(simX(:,1), simX(:,2), [], probColors, 'filled');
    % 
    % hold on
    % 
    % scatter(fixedPts(sinkIDx, 1), fixedPts(sinkIDx, 2), 'filled', 'r');
    % scatter(fixedPts(saddleIDx, 1), fixedPts(saddleIDx, 2), 'filled', 'g');
    % 
    % hold off
    % 
    % axis equal square
    % xlim(xLim);
    % ylim(yLim);
    % set(gca, 'XColor', 'w');
    % set(gca, 'YColor', 'w');
    % set(gca, 'ZColor', 'w');
    % set(gca, 'Color', 'k');
    % set(gca, 'GridColor', 'w');
    % grid on
    % box on
    % cb = colorbar('Color', 'w');
    % cb.Label.String = viewType;
    % set(gca, 'Clim', crange)
    % title(sprintf(['Finite Differences, t = %0.3f\n' ...
    %     'D_0 = %0.2f, D = %0.2f, dt = %0.4f, g = %0.4f'], ...
    %     t, D0, D, dt, scalarMetric), 'Color', 'w')

    drawnow
    pause(0.1);


end
