function compile_polygon_intersection_area

clc;

mex -v -O polygon_intersection_area.cpp ...
    CXXOPTIMFLAGS="-O3" ...
    CXXFLAGS="$CXXFLAGS -std=c++17" ...
    LDFLAGS="$LDFLAGS -fopenmp" ...
    -I/usr/include ...
    -I/usr/local/include ...
    -L/usr/lib:/usr/local/lib  -lboost_thread -lboost_system

end