function [TSchedule, allOptBasinProb, allOptProb, ensembleMaxProb, ...
    allTSchedules, basinIDx, maxBasinID] = ...
    fitTwoLandscapeFlipProtocol(X, T, initProb, ...
    maxNumFlips, basinLocIDx, maxBasinID, varargin)
%FITTWOLANDSCAPEFLIPPROTOCOL Determine a schedule for two landscapes that
%maximizes the cumulative basin probability for a single basin out of a set
%of possible basins
%
%   INPUT PARAMETERS:
%
%       - X:            #N x dim list of input points
%
%       - T:            #2 x 1 cell array of transition probability
%                       matrices
%
%       - initProb:     #N x 1 initial probability distribution
%
%       - maxNumFlips:  The maximum desired number of flips in the
%                       schedule. This method will exhaustively search all
%                       schdules with n <= maxNumFlips flips.
%
%       - basinLocIDx:  #B x 1 vector of basin location IDs (i.e. a set of
%                       indices into the point cloud 'X')
%
%       - maxBasinID:   The ID of the basin whose cumulative probability
%                       this method seeks to maximize. NOTE: This is an
%                       index into 'basinLocIDx'. This will be updated
%                       accordingly if basins need to be merged.
%
%   OPTIONAL INPUT PARAMETERS (Name, Value)-Pairs:
%
%       - ('NumSimTimes', numSimTimes = 500): The number of time steps to
%       run each simulation forward (i.e. the number of time steps in the
%       schedule)
%
%       - ('MinDuration', minDuration = 1): The minimum number of time
%       steps that must elapse before a flip is allowed.
%
%       - ('FirstLandscape', firstLandscapeID = -1): If this value is set
%       to '1' or '2' then all schedules that do not begin with the
%       corresponding landscape are rejected
%
%       - ('Verbose', verbose = false): Whether to produce verbose output
%
%   'evolveProbability' OPTIONS -------------------------------------------
%
%       - ('TimeStep', dt = 1): The time step accrued for each application
%       of the transition probability matrix.
%
%       - ('StrictNormalization', strictNormalization = true):  Whether or
%       not to re-normalize the probability at every step to avoid problems
%       with roundoff error
%
%       - ('UseGPU', useGPU = true): Whether or not to use the GPU to
%       accelerate time evolution
%
%   'computeBasins' OPTIONS -----------------------------------------------
%
%       - ('DistanceMatrix', distMatrix = []): #N x #N pairwise distance
%       matrix, i.e. distMatrix(i,j) is the distance between cell i and
%       cell j
%
%       - ('DistanceMethod', distMethod = 'euclidean'): The method by which
%       distance from each point in the cloud to a basin location is
%       calculated:
%                   
%           (1) 'euclidean' is just a raw Euclidean distance between points
%           (2) 'probability' computes the most probable path from each
%           point to each basin location using the transition matrix T and
%           then assigns points to basins according to which point-to-basin
%           transition is most probable
%
%       - ('ProbabilityThreshold', probThreshold = 0): The threshold above
%       which points are included in the aggregation of basin probabilities
%       (i.e. low probability points are not counted towards the total)
%
%       - ('MergeBasins', mergeBasins = {}): A cell array where each
%       elements contains a (non-intersecting) list of basins that will me
%       merged in the final output (this is subtly different than just
%       supplying an abbreviated list of input basins!). NOTE: Each element
%       of each basin is an index into 'basinLocIDx'. Each set of basins to
%       be merged will keep the ID of the FIRST basin in the corresponding
%       list
%
%   OUTPUT PARAMETERS:
%
%       - TSchedule:        1 x (numSimTimes-1) optimal schedule of
%                           transition matrix applications. Each element
%                           TSchedule(i) is the index into 'T' (1 or 2) of
%                           the matrix that was applied at that time point
%                           to reach the next time point
%
%       - allOptBasinProb:  #MB x numSimTimes array holding the (possibly
%                           merged) basin probabilities at each time point
%                           generated by the optimal schedule
%
%       - allOptProb:       #N x numSimTimes array holding the full
%                           probability vectors in the input point cloud
%                           generated by the optimal schedule
%
%       - ensembleMaxProb:  #MB x (#Schedules) array of the maximum
%                           probability observed in each basin for all
%                           admissible schedules
%
%       - allTSchedules:    (#Schedules) x (numSimTimes-1) ensemble of all
%                           admissible schedules
%
%       - basinIDx:         #N x 2 vector of basin IDs corresponding to the
%                           transition matrices in 'T' (NOTE: This is an
%                           index into 'basinLocIDx' (after mergers) NOT an
%                           index into the point cloud 'X')
%
%       - maxBasinID:       The ID of the basin whose cumulative
%                           probability this method seeks to maximize. If
%                           no mergers are are called this will be
%                           identical to the input.
%
%   by Dillon Cislo 2024/05/23

%--------------------------------------------------------------------------
% INPUT PROCESSING
%--------------------------------------------------------------------------
% Some more complete checks are performed inside the functions called
% during optimization

validateattributes(initProb, {'numeric'}, {'vector', 'finite', ...
    'nonnegative', 'real'}, 'fitTwoLandscapeFlipProtocol', 'initProb');
if (size(initProb, 2) ~= 1), initProb = initProb.'; end
numPoints = numel(initProb);
if (abs(sum(initProb)-1) > 1e-12)
    warning('Initial probabilities are NOT properly normalized');
end

if ~isempty(X)
    validateattributes(X, {'numeric'}, {'2d', 'finite', 'real', ...
        'nrows', numPoints}, 'fitTwoLandscapeFlipProtocol', 'X');
    numPoints = size(X,1); % dim = size(X,2);
end

assert(iscell(T), ['Transition operators must be supplied as a ' ...
    'cell array of matrices']);
assert(numel(T) == 2, 'This method can only handle two static landscapes');
cellfun(@(x) validateattributes(x, {'numeric'}, {'2d', 'finite', ...
    'real', 'nonnegative', 'nrows', numPoints, 'ncols', numPoints}), ...
    T, 'Uni', false);
checkNormT = cellfun(@(x) max(abs(1-sum(x,1))), T, 'Uni', true);
if (any(checkNormT > 1e-14))
    warnStr = sprintf(['The following transition matrices are not ' ...
        'properly normalized: ' repmat('%d ', [1 sum(checkNormT)])], ...
        find(checkNormT));
    warning(warnStr);
end

validateattributes(maxNumFlips, {'numeric'}, {'scalar', 'finite', ...
    'real', 'integer', '>=', 1}, ...
    'fitTwoLandscapeFlipProtocol', 'numFlips');

validateattributes(basinLocIDx, {'numeric'}, {'vector', 'finite', ...
    'positive', 'real', 'integer', '<=', numPoints}, ...
    'fitTwoLandscapeFlipProtocol', 'basinLocIDx');
if (size(basinLocIDx, 2) ~= 1), basinLocIDx = basinLocIDx.'; end

validateattributes(maxBasinID, {'numeric'}, {'scalar', 'integer', ...
    'finite', 'real', 'positive', '<=', numel(basinLocIDx)}, ...
    'fitTwoLandscapeFlipProtocol', 'maxBasinID');

% OPTIONAL INPUT PROCESSING -----------------------------------------------

numSimTimes = 500;
minDuration = 1;
firstLandscapeID = -1;
verbose = false;

dt = 1;
strictNormalization = true;
useGPU = true;

distMatrix = [];
distMethod = 'euclidean';
probThreshold = 0;
mergeBasins = {};

allDistMethods = {'euclidean', 'probability'};

supportedOptions = {'DistanceMatrix', 'DistanceMethod', ...
    'ProbabilityThreshold', 'MergeBasins', 'TimeStep', ...
    'StrictNormalization', 'UseGPU', 'NumSimTimes', ...
    'Verbose', 'MinDuration', 'FirstLandscape'};
checkSupportedOptions(supportedOptions, varargin);

for i = 1:length(varargin)

    if isa(varargin{i}, 'double'), continue; end
    if isa(varargin{i}, 'logical'), continue; end

    if strcmpi(varargin{i}, 'NumSimTimes')
        numSimTimes = varargin{i+1};
        validateattributes(numSimTimes, {'numeric'}, ...
            {'scalar', 'positive', 'integer', 'finite', 'real'}, ...
            'fitTwoLandscapeFlipProtocol', 'numSimTimes');
    end

    if strcmpi(varargin{i}, 'MinDuration')
        minDuration = varargin{i+1};
        validateattributes(minDuration, {'numeric'}, ...
            {'scalar', 'positive', 'integer', 'finite', 'real'}, ...
            'fitTwoLandscapeFlipProtocol', 'minDuration');
    end

    if strcmpi(varargin{i}, 'FirstLandscape')
        firstLandscapeID = varargin{i+1};
        validateattributes(firstLandscapeID, {'numeric'}, {'scalar', ...
            'finite', 'real'});
        if (firstLandscapeID <= 0), firstLandscapeID = -1; end
        assert(ismember(firstLandscapeID, [-1 1 2]), ...
            'Invalid first landscape ID supplied');
    end

    if strcmpi(varargin{i}, 'Verbose')
        verbose = varargin{i+1};
        validateattributes(verbose, {'logical'}, {'scalar'}, ...
            'fitTwoLandscapeFlipProtocol', 'verbose');
    end

    % 'evolveProbability' Options -----------------------------------------

    if strcmpi(varargin{i}, 'TimeStep')
        dt = varargin{i+1};
        validateattributes(dt, {'numeric'}, {'scalar', 'positive', ...
            'finite', 'real'}, 'fitTwoLandscapeFlipProtocol', 'dt');
    end

    if strcmpi(varargin{i}, 'StrictNormalization')
        strictNormalization = varargin{i+1};
        validateattributes(strictNormalization, {'logical'}, {'scalar'}, ...
            'fitTwoLandscapeFlipProtocol', 'strictNormalization');
    end

    if strcmpi(varargin{i}, 'UseGPU')
        useGPU = varargin{i+1};
        validateattributes(useGPU, {'logical'}, {'scalar'}, ...
            'fitTwoLandscapeFlipProtocol', 'UseGPU');
    end

    % 'computeBasins' Options ---------------------------------------------

    if strcmpi(varargin{i}, 'DistanceMatrix')
        distMatrix = varargin{i+1};
        if ~isempty(distMatrix)
            validateattributes(distMatrix, {'numeric'}, {'2d', ...
                'finite', 'real', 'nonnegative', 'square', ...
                'nrows', numPoints}, 'fitTwoLandscapeFlipProtocol', ...
                'distMatrix');
        end
    end

    if strcmpi(varargin{i}, 'DistanceMethod')
        distMethod = lower(varargin{i+1});
        validateattributes(distMethod, {'char'}, {'vector'}, ...
            'fitTwoLandscapeFlipProtocol', 'distMethod');
        assert(ismember(distMethod, allDistMethods), ...
            'Invalid distance method supplied');
    end

    if strcmpi(varargin{i}, 'ProbabilityThreshold')
        probThreshold = varargin{i+1};
        validateattributes(probThreshold, {'numeric'}, {'scalar', ...
            'finite', 'real'}, 'fitTwoLandscapeFlipProtocol', ...
            'probThreshold');
    end

    if strcmpi(varargin{i}, 'MergeBasins')
        mergeBasins = varargin{i+1};
        if (isvector(mergeBasins) && ~iscell(mergeBasins))
            mergeBasins = {mergeBasins};
        end
        assert(iscell(mergeBasins), ['List of basins to be merged ' ...
            'must be supplied either as a single vector of basin IDs ' ...
            'or a cell array of vectors of basin IDs']);
        mergeBasins = mergeBasins(:);
    end

end

if useGPU, try gpuDevice; catch, useGPU = false; end; end
assert(maxNumFlips < numSimTimes, ...
    'You can''t have more flips than time points')

%--------------------------------------------------------------------------
% COMPUTE BASINS FOR THE INPUT LANDSCAPES
%--------------------------------------------------------------------------

if verbose, fprintf('Computing basins... '); end

basinIDx = nan(numPoints, numel(T));
for i = 1:numel(T)

    [~, ~, basinIDx(:,i), ~] = computeBasins(X, T{i}, initProb, ...
    basinLocIDx, 'DistanceMatrix', distMatrix, ...
    'DistanceMethod', distMethod, 'MergeBasins', mergeBasins, ...
    'ProbabilityThreshold', probThreshold);

end

assert(isequal(unique(basinIDx(:,1)), unique(basinIDx(:,2))), ...
    'Basin assignment mismatch for supplied landscapes');

numBasins = numel(unique(basinIDx(:,1)));
maxBasinID = basinIDx(basinLocIDx(maxBasinID), 1);

if verbose, fprintf('Done\n'); end

%--------------------------------------------------------------------------
% ENUMERATE ALL ADMISSIBLE SCHEDULES
%--------------------------------------------------------------------------

if verbose, fprintf('Enumerating all possible schedules... '); end

flipLocations = nchoosek(1:(numSimTimes-1+maxNumFlips), maxNumFlips);
flipLocations = full(sparse(repmat(1:size(flipLocations,1), [1 maxNumFlips]), ...
    flipLocations, 1, size(flipLocations,1), numSimTimes-1+maxNumFlips));

tmpTSchedules = cumsum(flipLocations, 2);
allTSchedules = zeros(size(flipLocations, 1), numSimTimes-1);
for i = 1:size(allTSchedules, 1)
    allTSchedules(i,:) = tmpTSchedules(i, ~flipLocations(i,:));
end
allTSchedules = [mod(allTSchedules, 2); mod(allTSchedules+1, 2)]+1;
allTSchedules = unique(allTSchedules, 'rows');

clear tmpTSchedules flipLocations

if verbose, fprintf('Done\n'); end

% Remove schedules with contiguous blocks smaller than the minumum duration
% threshold
if (minDuration > 1)

    if verbose, fprintf('Removing inadmissible schedules... '); end

    flipLocations = [true(size(allTSchedules,1), 1), ...
        allTSchedules(:, 2:end) ~= allTSchedules(:, 1:(end-1))];
    flipLocations = circshift(flipLocations, [0, -1]);
    flipLocations = mat2cell(flipLocations, ...
        ones(1, size(allTSchedules,1)), size(allTSchedules,2));

    regionSizes = repmat({1:(numSimTimes-1)}, size(allTSchedules, 1), 1);
    regionSizes = cellfun(@(x,y) max(1, diff([0 x(y)], 1, 2)), ...
        regionSizes, flipLocations, 'Uni', false);

    rmIDx = cellfun(@(x) any(x < minDuration), regionSizes, ...
        'Uni', true);

    allTSchedules(rmIDx, :) = [];

    clear regionSizes flipLocations rmIDx

    
    if verbose, fprintf('Done\n'); end

end

% Remove schedules that do not correspond to the user specified first
% landscape
if (firstLandscapeID > 0)
    allTSchedules(allTSchedules(:,1) ~= firstLandscapeID, :) = [];
end

%--------------------------------------------------------------------------
% SEARCH OVER ADMISSIBLE SCHEDULES
%--------------------------------------------------------------------------

TSchedule = zeros(1, numSimTimes-1);
allOptBasinProb = -inf(numBasins, numSimTimes);
allOptProb = nan(numPoints, numSimTimes);
ensembleMaxProb = zeros(numBasins, size(allTSchedules, 1));

if verbose, disp('Searching over admissible schedules:'); end
for i = 1:size(allTSchedules, 1)

    if verbose, progressbar(i, size(allTSchedules, 1)); end

    curProb = evolveProbabilities(initProb, T, allTSchedules(i,:), ...
        'NumViewTimes', -1, 'TimeStep', dt, 'UseGPU', useGPU, ...
        'StrictNormalization', strictNormalization);

    curBasinProb = zeros(numBasins, numSimTimes);
    for tidx = 1:numSimTimes

        curBasinIDx = basinIDx(:, allTSchedules(i, max(1, tidx-1)));

        if (probThreshold > 0)

            incPointIDx = curProb > probThreshold;
            curBasinProb(:, tidx) = accumarray( ...
                curBasinIDx(incPointIDx, tidx), curProb(incPointIDx), ...
                [numBasins 1] );

        else

            curBasinProb(:, tidx) = accumarray( curBasinIDx, ...
                curProb(:, tidx), [numBasins 1] );

        end

    end

    ensembleMaxProb(:, i) = max(curBasinProb, [], 2);

    if (max(curBasinProb(maxBasinID, :)) > ...
            max(allOptBasinProb(maxBasinID, :)))

        TSchedule = allTSchedules(i,:);
        allOptBasinProb = curBasinProb;
        allOptProb = curProb;

    end

end

end

